/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_prog4;

import DAL.Gebruiker;
import DAL.Gerechten;
import Services.AanmakenList;
import Services.Zoeken;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author Benjamin
 */
public class Afrekenen extends javax.swing.JFrame {
    
ArrayList<String> naam = new ArrayList<>();
ArrayList<String> gerechten = new ArrayList<>();
Zoeken zoek =  new Zoeken();

    /**
     * Creates new form Afrekenen
     */
    public Afrekenen() {
        initComponents();
        GebruikerList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lsbGebruiker = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsbBestelling = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lsbGebruiker.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lsbGebruiker.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsbGebruikerValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lsbGebruiker);

        jLabel1.setText("Gebruikers");

        lsbBestelling.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lsbBestelling.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsbBestellingValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lsbBestelling);

        jLabel2.setText("Bestelde Gerechten");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnPay.setText("Pay");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnPay))
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        this.setVisible(false);
        new Betaling().setVisible(true);
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void lsbGebruikerValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsbGebruikerValueChanged
        if(lsbGebruiker.getSelectedIndex() != -1)
        {
            Gebruiker gebruiker = zoek.ZoekGebruikerDoorNaam(naam.get(lsbGebruiker.getSelectedIndex()));
            GerechtenList(gebruiker);
            
        }
    }//GEN-LAST:event_lsbGebruikerValueChanged

    private void lsbBestellingValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsbBestellingValueChanged
//<<<<<<< HEAD
////        if(lsbBestelling.getSelectedIndex() != -1)
////        {
////            Gerechten ger = zoek.ZoekGerechtByName(naam.get(lsbBestelling.getSelectedIndex()));
////            GerechtenList(ger);
//////            GebruikerList(ger);
////        }
//=======
//        
//>>>>>>> origin/master
    }//GEN-LAST:event_lsbBestellingValueChanged

    private void GebruikerList()
    {
        try {
            naam.clear();
            AanmakenList list = new AanmakenList();
            List<Gebruiker> GebruikerList = list.ListGebruiker();
            GebruikerList.stream().forEach((g) -> {
                naam.add(g.getNaam());
            });
            lsbGebruiker.setListData(naam.toArray());
            lsbBestelling.setListData(gerechten.toArray());
        } catch (Exception e) {
        }
    }
    
    private void GerechtenList(DAL.Gebruiker gebruiker)
    {
        try {
            gerechten.clear();
            lsbBestelling.setListData(gerechten.toArray());
            AanmakenList list = new AanmakenList();
            List<Gerechten> GerechtenList = list.ProductByGebruikerList(gebruiker);
            GerechtenList.stream().forEach((g) -> {
                gerechten.add(g.getGerechtNaam() + " " + g.getTotaal());
            });
            lsbBestelling.setListData(gerechten.toArray());
        } catch (Exception e) {
        }
    }
    
//    private void Refresh()
//    {
//        AanmakenList lijst = new AanmakenList();
//        int geb = lijst.ListGebruiker().size();
//        int ger = lijst.ListGerechten().size();
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Afrekenen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Afrekenen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Afrekenen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Afrekenen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Afrekenen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lsbBestelling;
    private javax.swing.JList lsbGebruiker;
    // End of variables declaration//GEN-END:variables
}
