/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_prog4;

import DAL.Gebruiker;
import Services.AanmakenList;
import Services.Delete;
import Services.Opslaan;
import Services.Update;
import Services.Zoeken;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Benjamin
 */
public class GebruikersFrame extends javax.swing.JFrame {

    
    Opslaan opslaan = new Opslaan();
    AanmakenList aanmakenList = new AanmakenList();
    Delete delete = new Delete();
    Zoeken zoek = new Zoeken();
    Update update = new Update();
    ArrayList<String> naam = new ArrayList<>();
    boolean edit = false;
    /**
     * Creates new form GebruikersFrame
     */
    public GebruikersFrame() {
        initComponents();
        RefreshList();
        btnSave.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lsbGebruiker = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGebruikersnaam = new javax.swing.JTextField();
        txtWachtwoord = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnEditGebruiker = new javax.swing.JButton();
        btnNewGebruiker = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lsbGebruiker.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lsbGebruiker.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsbGebruikerValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lsbGebruiker);

        jLabel1.setText("ID");

        jLabel2.setText("Gebruikersnaam:");

        jLabel3.setText("Wachtwoord:");

        txtGebruikersnaam.setText("jTextField1");

        txtWachtwoord.setText("jTextField2");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEditGebruiker.setText("Edit");
        btnEditGebruiker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditGebruikerActionPerformed(evt);
            }
        });

        btnNewGebruiker.setText("New");
        btnNewGebruiker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGebruikerActionPerformed(evt);
            }
        });

        txtID.setText("jTextField1");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWachtwoord, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(txtGebruikersnaam)
                            .addComponent(txtID)))
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditGebruiker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewGebruiker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtGebruikersnaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtWachtwoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditGebruiker)
                        .addGap(18, 18, 18)
                        .addComponent(btnNewGebruiker)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            if(edit == true)
            {
                Gebruiker g = new Gebruiker();
                g.setId(Long.parseLong(txtID.getText()));
                g.setNaam(txtGebruikersnaam.getText());
                g.setPassword(txtWachtwoord.getText());
                boolean result = update.UpdateGebruikers(g);
                if(result == true)JOptionPane.showMessageDialog(null, "Update gelukt");
                else JOptionPane.showMessageDialog(null, "update niet gelukt");
            }
            else if(edit == false)
            {
                Gebruiker g = new Gebruiker();
                g.setNaam(txtGebruikersnaam.getText());
                g.setPassword(txtWachtwoord.getText());
                int result = opslaan.OpslaanGebruiker(g);
                if(result == 1)
                {
                    JOptionPane.showMessageDialog(null, "Er was een probleem");
                }
                else if (result == 2)
                {
                    JOptionPane.showMessageDialog(null, "Bestaat reeds");
                }
                else 
                {
                    JOptionPane.showMessageDialog(null, "Opslage geslaagd");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Onbekende fout");
            }
            
            txtGebruikersnaam.setEnabled(false);
            txtWachtwoord.setEnabled(false);
            btnEditGebruiker.setVisible(true);
            btnNewGebruiker.setVisible(true);
            btnSave.setVisible(true);
            txtGebruikersnaam.setText("");
            txtID.setText("");
            txtWachtwoord.setText("");
            RefreshList();
           
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditGebruikerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditGebruikerActionPerformed
        if(lsbGebruiker.getSelectedIndex() != -1)
        {
            txtGebruikersnaam.setEnabled(true);
            txtWachtwoord.setEnabled(true);
            btnEditGebruiker.setVisible(false);
            btnNewGebruiker.setVisible(false);
            btnSave.setVisible(true);
            edit = true;
        }
        else 
        {
            JOptionPane.showMessageDialog(null, "Geen item geselecteerd");
        }
    }//GEN-LAST:event_btnEditGebruikerActionPerformed

    private void btnNewGebruikerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGebruikerActionPerformed
        txtGebruikersnaam.setEnabled(true);
        txtWachtwoord.setEnabled(true);
        btnEditGebruiker.setVisible(false);
        btnNewGebruiker.setVisible(false);
        btnSave.setVisible(true);
        
        txtGebruikersnaam.setText("");
        txtID.setText("");
        txtWachtwoord.setText("");
        edit = false;
    }//GEN-LAST:event_btnNewGebruikerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new MainFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void lsbGebruikerValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsbGebruikerValueChanged
        if(lsbGebruiker.getSelectedIndex() != -1)
        {
            Gebruiker gebruikerresultaat = zoek.ZoekGebruikerDoorNaam(naam.get(lsbGebruiker.getSelectedIndex()));
            txtGebruikersnaam.setText(gebruikerresultaat.getNaam());
            txtWachtwoord.setText(gebruikerresultaat.getPassword());
            txtID.setText(Long.toString(gebruikerresultaat.getId()));
        }
    }//GEN-LAST:event_lsbGebruikerValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GebruikersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GebruikersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GebruikersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GebruikersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GebruikersFrame().setVisible(true);
            }
        });
    }
    
    private void RefreshList()
    {
        try 
            {
                naam.clear();
                List<Gebruiker> Gebruikerlist = aanmakenList.ListGebruiker();
                for(Gebruiker g: Gebruikerlist)
                {
                    naam.add(g.getNaam());
                }
                lsbGebruiker.setListData(naam.toArray());
        
            } 
        catch (Exception e) {}
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEditGebruiker;
    private javax.swing.JButton btnNewGebruiker;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lsbGebruiker;
    private javax.swing.JTextField txtGebruikersnaam;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtWachtwoord;
    // End of variables declaration//GEN-END:variables
}
