/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_prog4;

import DAL.Gerechten;
import Services.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Benjamin
 */
public class GerechtenFrame extends javax.swing.JFrame {
    
    Opslaan opslaan = new Opslaan();
    AanmakenList aanmakenList = new AanmakenList();
    Delete delete = new Delete();
    Zoeken zoek = new Zoeken();
    Update update = new Update();
    ArrayList<String> naam = new ArrayList<>();
    boolean edit = false;

    /**
     * Creates new form GerechtenFrame
     */
    public GerechtenFrame() {
        initComponents();
        RefreshList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lsbGerechten = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtGerechtID = new javax.swing.JTextField();
        txtGerechtNaam = new javax.swing.JTextField();
        txtGerechtPrijs = new javax.swing.JTextField();
        txtGerechtVoorraad = new javax.swing.JTextField();
        txtGerechtAantalBesteld = new javax.swing.JTextField();
        txtGerechtTotaal = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lsbGerechten.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lsbGerechten.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsbGerechtenValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lsbGerechten);

        jLabel1.setText("Gerecht ID");

        jLabel2.setText("Gerecht Naam");

        jLabel3.setText("Gerecht Prijs");

        jLabel4.setText("Voorraad");

        jLabel5.setText("# bestellen");

        jLabel6.setText("Totaal");

        txtGerechtID.setEditable(false);
        txtGerechtID.setText("jTextField1");

        txtGerechtNaam.setText("jTextField2");

        txtGerechtPrijs.setText("jTextField3");

        txtGerechtVoorraad.setText("jTextField4");

        txtGerechtAantalBesteld.setText("jTextField5");

        txtGerechtTotaal.setText("jTextField6");

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGerechtPrijs, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGerechtVoorraad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 1, Short.MAX_VALUE)
                                .addComponent(txtGerechtTotaal, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtGerechtAantalBesteld)
                            .addComponent(txtGerechtNaam)
                            .addComponent(txtGerechtID)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNew)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBack))
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtGerechtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtGerechtNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtGerechtPrijs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtGerechtVoorraad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtGerechtAantalBesteld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtGerechtTotaal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNew)
                            .addComponent(btnEdit)
                            .addComponent(btnDelete)
                            .addComponent(btnBack))
                        .addGap(18, 18, 18)
                        .addComponent(btnSave)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        edit = false;
        EnableText();
        DisableButton();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try
        {
            if(edit == false)
            {
                Gerechten gerechten  = new Gerechten();
                gerechten.setGerechtNaam(txtGerechtNaam.getText());
                gerechten.setGerechtPrijs(Double.parseDouble(txtGerechtPrijs.getText()));
                gerechten.setTotaal(Integer.parseInt(txtGerechtTotaal.getText()));
                int result = opslaan.OpslaanGerechten(gerechten);
                if(result == 1)
                {
                    JOptionPane.showMessageDialog(null, "Er was een probleem");
                }
                else if (result == 2)
                {
                    JOptionPane.showMessageDialog(null, "Dit gerecht bestaat reeds");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Done");
                    RefreshList();
                    DisableText();
                    EnableButton();
                }
            }
            
            else if(edit == true)
            {
                Gerechten g =  new Gerechten();
                g.setGerechtNaam(txtGerechtNaam.getText());
                g.setGerechtPrijs(Double.parseDouble(txtGerechtPrijs.getText()));
                g.setTotaal(Integer.parseInt(txtGerechtTotaal.getText()));
                g.setId(Long.parseLong(txtGerechtID.getText()));
                boolean result = update.UpdateGerecht(g);
                if(result == true)
                {
                    JOptionPane.showMessageDialog(null, "Update gelukt");
                    RefreshList();
                    DisableText();
                    EnableButton();
                }
                
                else 
                {JOptionPane.showInternalMessageDialog(null, "Update gefaald");}
            }
            else
                    {
                        JOptionPane.showMessageDialog(null,"Er is een overwachte fout opgedoken, gelieve contact op te nemen met u beheerder");
                    }
        }
        catch(Exception ex){JOptionPane.showInternalMessageDialog(null, "Er is een probleem bij u ingave" + ex.getMessage());}
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if(lsbGerechten.getSelectedIndex() != -1)
        {
            edit = true;
            txtGerechtTotaal.setEnabled(true);
            txtGerechtNaam.setEnabled(true);
            txtGerechtPrijs.setEnabled(true);
            txtGerechtVoorraad.setEnabled(true);
            DisableButton();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "niet geselecteerd");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(lsbGerechten.getSelectedIndex() != -1)
        {
            delete.DeleteGerechten(Integer.parseInt(txtGerechtID.getText()));
            DisableText();
            RefreshList();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void lsbGerechtenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsbGerechtenValueChanged
//        int result = lsbGerechten.getSelectedIndex();
//        Gerechten gerechtenresultaat = zoek.ZoekGerechtByName(naam.get(result));
//        txtGerechtTotaal.setText(Integer.toString(gerechtenresultaat.getTotaal()));
//        txtGerechtID.setText(Long.toString(gerechtenresultaat.getId()));
//        txtGerechtPrijs.setText(Double.toString(gerechtenresultaat.getGerechtPrijs()));
//        txtGerechtVoorraad.setText(Integer.toString(gerechtenresultaat.getGerechtenVoorraad()));
//        txtGerechtAantalBesteld.setText(Integer.toString(gerechtenresultaat.getGerechtenAantalBesteld()));
//        txtGerechtNaam.setText(gerechtenresultaat.getGerechtNaam());
          Box();
        
    }//GEN-LAST:event_lsbGerechtenValueChanged

    private void RefreshList()
    {
        try 
            {
                naam.clear();
                AanmakenList list = new AanmakenList();
                List<Gerechten> GerechtenList = list.ListGerechten();
                for(Gerechten g: GerechtenList)
                {
                    naam.add(g.getGerechtNaam());
                }
                lsbGerechten.setListData(naam.toArray());
                lsbGerechten.setSelectedIndex(0);
                Box();
        
            } 
        catch (Exception e) {}
    }
    
    private void DisableButton()
    {
      
        btnDelete.setVisible(false);
        btnEdit.setVisible(false);
        btnNew.setVisible(false);
        btnSave.setVisible(true);
    }
    
    public void EnableButton()
    {
        btnDelete.setVisible(true);
        btnEdit.setVisible(true);
        btnNew.setVisible(true);
        btnSave.setVisible(false);
    }
    
    private void DisableText()
    {
        txtGerechtID.setText("");
        txtGerechtNaam.setEnabled(false);
        txtGerechtPrijs.setEnabled(false);
        txtGerechtTotaal.setEnabled(false);
        
        txtGerechtNaam.setText("");
        txtGerechtPrijs.setText("");
        txtGerechtVoorraad.setText("");
        txtGerechtTotaal.setText("");
    }
    
    private void EnableText()
    {
        txtGerechtID.setText("");
        txtGerechtNaam.setEnabled(true);
        txtGerechtPrijs.setEnabled(true);
        txtGerechtTotaal.setEnabled(true);
        
        txtGerechtNaam.setText("");
        txtGerechtPrijs.setText("");
        txtGerechtVoorraad.setText("");
        txtGerechtTotaal.setText("");
    }
    
//    private void EnableButton()
//    {
//        btnDelete.setVisible(true);
//        btnEdit.setVisible(true);
//        btnNew.setVisible(true);
//        btnSave.setVisible(false);
//    }
    
    private void Box()
    {
        if(lsbGerechten.getSelectedIndex() != -1)
        {
            int res = lsbGerechten.getSelectedIndex();
            Gerechten rgerechten = zoek.ZoekGerechtByName(naam.get(res));
            txtGerechtTotaal.setText(Integer.toString(rgerechten.getTotaal()));
            txtGerechtID.setText(Long.toString(rgerechten.getId()));
            txtGerechtNaam.setText(rgerechten.getGerechtNaam());
            txtGerechtPrijs.setText(Double.toString(rgerechten.getGerechtPrijs()));
            txtGerechtAantalBesteld.setText(Integer.toString(rgerechten.getGerechtenAantalBesteld()));
            txtGerechtVoorraad.setText(Integer.toString(rgerechten.getGerechtenVoorraad()));
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerechtenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerechtenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerechtenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerechtenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerechtenFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lsbGerechten;
    private javax.swing.JTextField txtGerechtAantalBesteld;
    private javax.swing.JTextField txtGerechtID;
    private javax.swing.JTextField txtGerechtNaam;
    private javax.swing.JTextField txtGerechtPrijs;
    private javax.swing.JTextField txtGerechtTotaal;
    private javax.swing.JTextField txtGerechtVoorraad;
    // End of variables declaration//GEN-END:variables

    
}
